version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=foo
      - REDIS_PORT=6379
      - REDIS_ARGS=""
    networks:
      - default

volumes:
  redisdata:
    driver: local

    