version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=foo
      - REDIS_PORT=6379
      - REDIS_ARGS=""
    networks:
      - default

  ##############################################################################################################
  # Redis commander on port 8081
  ##############################################################################################################
  redis_commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  redisdata:
    driver: local


    