version: "3.9"
secrets:
  WEBAPP_ENV:
    file: ./secrets/WEBAPP_ENV
services:
  webapp:
    image: create-a-report:${TAG:-latest}
    build:
      context: ../
      dockerfile: dockerfile
      args:
        - GA_ID
    ports:
      - "8000:8000"
    secrets:
      - WEBAPP_ENV
    entrypoint: [ '/bin/sh', '-c', "source /run/secrets/WEBAPP_ENV && npm run start" ]