version: "3.9"
services:
  webapp:
    image: create-a-report:${TAG:-latest}
    build:
      context: ../
      dockerfile: dockerfile
      args:
        - GA_ID
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379